function [position, meas, measCov, trackpos, trackCov, trackids] = readData(scenario,dets, tracks)
%% Using Hampton University Skyler Radar Sensor's dataset to track drones
% Work done at TAN's LAB (Time-sensitive networking (T), 
%                           AI-driven cybersecurity (A), 
%                    NextG communication networking (N), 
%         Time-series Analysis via Network science (TAN))
% Generated by MATLAB(R) 9.13 (R2022b) and Sensor Fusion and Tracking Toolbox 2.3 (R2022b).
% Generated on: 16-May-2022 16:43:53

allDets = [dets{:}];

if ~isempty(allDets)
    % extract column vector of measurement positions
    meas = cat(2,allDets.Measurement)';

    % extract measurement noise
    measCov = cat(3,allDets.MeasurementNoise);
else
    meas = zeros(0,3);
    measCov = zeros(3,3,0);
end

if ~isempty(tracks)
        [trackpos,trackCov] = getTrackPositions(tracks,'constvel');
        trackids = arrayfun(@(x) string(x.TrackID), tracks');
else
    trackpos = zeros(0,3);
    trackCov = zeros(3,3,0);
    trackids ={};
end


truePoses = platformPoses(scenario);
position = vertcat(truePoses(:).Position);
end